### ISSUE TITLE
Uploading a large file has a huge impact on memory

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/something-awesome#176]
[Affected versions]:
- Nightly 56

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a large file and open the Task Manager.
3. Sort by Memory and observe the Nightly process.

[Expected result]:
- Low to moderate memory impact.

[Actual results]:
- Memory usage is ~2GB.

[Notes]:
- Here is a Firefox memory profile while the issue is manifesting on Windows:  
[memory-report-windows.json.gz](https://github.com/mozilla/something-awesome/files/1135966/memory-report-windows.json.gz)
- Mac memory report:
[memory-report-mac.json.gz](https://github.com/mozilla/something-awesome/files/1135815/memory-report-mac.json.gz)
- Linux memory report:
[memory-report-linux.json.gz](https://github.com/mozilla/something-awesome/files/1135962/memory-report-linux.json.gz)
- Here is a screen recording with the issue:
![high memory usage when uploading a large file](https://user-images.githubusercontent.com/18304511/28022479-fce80fa6-6593-11e7-9e43-5148540a4d9a.gif)

**Comment by wresuolc** [comment]
With the way we are processing files this is expected behavior.  We are considering looking into chunking/streaming in v2

**Comment by pdehaan** [comment]
@SoftVision-CiprianMuresan Do you remember how "large" the large file was? 100MB? 1GB?

**Comment by SoftVision-PaulOiegas** [comment]
@pdehaan almost 2GB. You can see that in the screen recording.

**Comment by pdehaan** [comment]
Also see https://github.com/mozilla/something-awesome/issues/170#issuecomment-314107793, which has an excellent breakdown of different browser behaviors when trying to upload 1-2GB files.

I'll argue that since the behavior leans more towards crashing in certain browsers, we should at least  put some note in the UI that sending files over X megabytes may not work as expected, depending on browsers.

Also, maybe we should start an FAQ.md file where we answer some [soon to be] commonly asked questions.

**Comment by SoftVision-PaulOiegas** [comment]
Agree on that, users should be notified about the behavior/risk.
