### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by dannycoates** [mozilla/something-awesome#65]

**Comment by abhinadduri** [comment]
Finished adding analytics with a personal account; we still have to switch out to a production account.

**Comment by bmintz** [comment]
Why would you do this on a privacy oriented site?

**Comment by TwizzyDizzy** [comment]
I'm also quite irritated by this. The reason for having send in the first place is usually, that I don't want to use dropbox or wetransfer or the likes because I don't trust them (read 3rd party entities) with my data.

Hosting it yourself and then having your stuff sent off to google seems VERY counter-intuitive.

Cheers
Thomas

**Comment by chuckharmston** [comment]
@TwizzyDizzy In order to gather usage information that will help us make determinations about the future of Send (which is, after all, just an experiment), and Google Analytics is the best option for us at this time. We have a strong and fair [privacy policy](https://www.mozilla.org/en-US/privacy/websites/), and have [publicly-documented](https://github.com/mozilla/send/blob/master/docs/metrics.md) all the data we collect.

Of note, we use GA's [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/) instead of the tracking pixel, so they only receive that information that we've chosen to send them, rather than giving them ambient browsing data. Additionally, we've [worked with Google](https://bugzilla.mozilla.org/show_bug.cgi?id=697436#c14) to ensure that user data from Mozilla's properties are not aggregated or tied back to other data they may be collecting from other sites. We also respect [Do Not Track](https://support.mozilla.org/kb/how-do-i-turn-do-not-track-feature), and will not send anything if it's enabled.

**Comment by dannycoates** [comment]
Also, using Private Browsing Mode automatically opts out of analytics on https://send.firefox.com

> Hosting it yourself and then having your stuff sent off to google seems VERY counter-intuitive.

If by "hosting it yourself" you mean hosting the Send code on your own server then you have full control over analytics. If you don't set a `GOOGLE_ANALYTICS_ID` explicitly you won't report analytics anywhere.

**Comment by immanuelfodor** [comment]
FYI, it seems the GA config option is no longer in use:
- https://github.com/mozilla/send/issues/897
- https://github.com/mozilla/send/search?q=analytics
- https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsend.firefox.com%2F#requests
