### ISSUE TITLE
Update encryption format to use gcm

### ISSUE THREAD

**Issue by wresuolc** [mozilla/something-awesome#86]
We should be using GCM.  Details are at  https://www.w3.org/TR/WebCryptoAPI/#aes-gcm .  Use a 256 bits key + additional data (aad) + IV, all random and unique to each file.  Put the aad and iv in the file metadata, keep the key secret in the fragment.

Ping @jvehent for review

**Comment by dannycoates** [comment]
GCM means we'll work on fewer browsers, right? Is that a worthwhile trade off? I don't deeply understand what disadvantage we're trying to avoid from CBC. I know that it's "less recommended" than GCM but in this use case of 24h storage is it a deal breaker? I'd prefer to support as many browsers (and versions, including mobile) as reasonable.

**Comment by jvehent** [comment]
The main benefit of GCM over CBC is the added layer of authentication that guarantees the integrity of the message. With CBC, you could decrypt something with the key, thinking you got the original, only to end up with data that's completely different from what you'd expect. GCM's authentication prevents that.

You could achieve the same authentication with CBC by adding an HMAC with the secret key, but I think using the current crypto standard instead of the old one sends a better message.

I don't know about browser compatibility. This is a valid point I cannot answer.

**Comment by jvehent** [comment]
Another option might be to use a standard encryption format, like JWE: https://tools.ietf.org/html/rfc7516

**Comment by jvehent** [comment]
See also https://github.com/mozilla/notes/pull/77 for an example of using the `js-jose` library to encrypt data with JWE AES256-GCM.

**Comment by abhinadduri** [comment]
@jvehent I have pushed a 256 bit gcm encryption scheme to the gcm branch. Please check it out and let me know if there are changes that need to be made. I've also gotten it to work on all modern browsers (Chrome, Firefox, Edge, and Safari). I have not tested it on Opera yet.

**Comment by jvehent** [comment]
@abhinadduri Could you use JWE with the `js-jose` library? It's an encryption standard that would default to aes256-gcm and be easier to integrate in other libraries.

**Comment by dannycoates** [comment]
JWE (and js-jose in particular) isn't ideal for our use case of encrypting large files. I did up a test with it and the amount of string conversion and manipulation made it *very* slow. The one part it made nicer was that key parameters were handled for you.

Using a JWE for the metadata and KW of the encryption key might be a good idea and easily stored in redis, with the file data as raw encrypted binary. That'd give us the benefits of using the lib for key management and limiting our `crypto.subtle` use to `encrypt` and `decrypt` of the file.

**Comment by dannycoates** [comment]
@ekr, I've updated the [flow diagram doc](https://docs.google.com/document/d/1on7lt_6gX6ua4ER-ntHFgkvQ3vzvBuWLTGN4Mr4ouNA/edit#), adding a section about our security assumptions. I'm not sure how formal it should to be so I started with just a short summary, but I'm happy to make changes to satisfy concerns. Feel free to leave comments in the doc.

**Comment by ekr** [comment]
This looks reasonably sound. I've made some comments. 

I don't think you need JOSE.

**Comment by dannycoates** [comment]
done in #106

**Comment by NicoHood** [comment]
Does this use 128 or 256bit AES-GCM? It seems to me it still uses 128bit Keys. this should be changed if possible.

**Comment by ekr** [comment]
Why should this be changed to 256-bit AES?

**Comment by ekr** [comment]
"stronger" isn't inherently an argument. Otherwise, we should use triple-AES-256 (a la Triple-DES), etc.

Here, for example, are the BSI recommendations from 2017, which include 128 bit keys out past 2022: https://www.keylength.com/en/8/

We might want to at some point go to AES-256 in the service of quantum resistance, but it's not really obvious how much that helps given the channels the keys are going through
