### ISSUE TITLE
Ensure IP is anonymized in Google Analytics

### ISSUE THREAD

**Issue by wresuolc** [mozilla/something-awesome#92]

**Comment by groovecoder** [comment]
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp

**Comment by fmarier** [comment]
You'll probably want to truncate the Referrer as well: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#referrer

in order to avoid accidentally collecting user's social identities.

This is something that [Firefox Screenshots did too](https://github.com/mozilla-services/screenshots/issues/2717).

**Comment by abhinadduri** [comment]
Added in pr #111 and truncated referrer in 87bdb7a (committed to master)
